server:
  ip: 127.0.0.1
  port: 8080

coin:
  name: Viacoin
  symbol: via
  algo: scrypt
  blocktime: 24

rpc:
  ip: 127.0.0.1
  username: via1
  password: via
  port: 5222

zmq:
  endpoint: tcp://127.0.0.1:28332

mongo:
  ip: 127.0.0.1
