server:
  ip: 127.0.0.1
  port: 8000

coin:
  name: Viacoin
  symbol: via
  algo: scrypt
  blocktime: 24

rpc:
  ip: 127.0.0.1
  username: via
  password: via
  port: 5222

zmq:
  hashblock: tcp://127.0.0.1:2835
  rawblock: tcp://127.0.0.1:3002
  rawtx: tcp://127.0.0.1:3002